version: '2.35.1'

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    ports:
      - "80:800"  # Прослушивает порты 80 хоста и контейнера
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/serega-sosi.ru:/etc/letsencrypt/live/serega-sosi.ru:ro
      - /etc/letsencrypt/archive/serega-sosi.ru:/etc/letsencrypt/archive/serega-sosi.ru:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
    depends_on:
      - web
