version: '2.35.1'

services:
  web:
    build: .
    ports:
      - "80:80"  # Пробрасываем порт 80 сервера на 80 порт контейнера
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
      image: nginx:latest
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - web