version: '2.35.1'

services:
  web:
    build: .
    ports:
      - "8000:80"  # Порт 8000 хост-системы перенаправляется на порт 80 контейнера
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Прослушивает порты 80 хоста и контейнера
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
